export default {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_ERROR: "SET_ERROR",
  SIGN_UP_USER: "SIGN_UP_USER",
  VERIFY_USER: "VERIFY_USER",
  SIGN_IN_USER: "SIGN_IN_USER",
  SIGN_OUT_USER: "SIGN_OUT_USER",
};
