export const LOAD_PROFILE = "LOAD_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const LOAD_USER_ARTICLES = "LOAD_USER_ARTICLES";
export const LOAD_USER_FOLLOWERS = "LOAD_USER_FOLLOWERS";
export const LOAD_USERS_FOLLOWED = "LOAD_USER_FOLLOWED";
export const FOLLOW_OR_UNFOLLOW_USER = "FOLLOW_OR_UNFOLLOW_USER";
export const RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
export const NOT_AUTHORIZED = "NOT_AUTHORIZED";
